### ISSUE TITLE
Minor mistake

### ISSUE THREAD

**Issue by felixendres** [kenjihiranabe/The-Art-of-Linear-Algebra#1]
Great pdf, thanks.

I think the sentence "The four subspaces consists of N(A) + C(A^T) (which are perpendicular to each other) in R^n and N(A^T)
+ N(A) in R^m" on page 3 should be "... N(A^T) + C(A) ..." , shouldn't it?

**Comment by kenjihiranabe** [comment]
Nice catch! corrected. thanks.
