### ISSUE TITLE
A Small Typo in The Chinese Version of The Art of Linear Algebra

### ISSUE THREAD

**Issue by Elenquesse** [kenjihiranabe/The-Art-of-Linear-Algebra#14]
In section 6.4, a symmetric matrix S (对称矩阵S) seems to be typed as 对乘矩阵S. This appears on [line 578](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/blob/main/The-Art-of-Linear-Algebra-zh-CN.tex#L578) of `The-Art-of-Linear-Algebra-zh-CN.tex`

**Comment by kenjihiranabe** [comment]
@kf-liu Can you work on this ?

**Comment by kf-liu** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，谢谢！

**Comment by kf-liu** [comment]
> @kf-liu Can you work on this ?

sure
