### ISSUE TITLE
中文勘误

### ISSUE THREAD

**Issue by dlutleixin** [kenjihiranabe/The-Art-of-Linear-Algebra#16]
## 修正第3页上的英文大小写

修正前：

> \begin{itemize}
  \item 1.1节 (p.3) LInear combinations
  \item 1.3节 (p.21) Matrices and Column Spaces
\end{itemize} 

修正后：

> \begin{itemize}
  \item 1.1节 (p.3) Linear combinations
  \item 1.3节 (p.21) Matrices and Column Spaces
\end{itemize} 

## 修正第8页上图13无法显示中文

修正前：
> \caption{$A的递归秩1矩阵分离$}

修正后：

> \caption{$A$的递归秩1矩阵分离}

## 修正第9页上的中文名词
修正前：

> 一个对乘矩阵$S$通过一个正交矩阵$Q$和它的转置矩阵, 对角化为$\Lambda$. 

修正后：

> 一个对称矩阵$S$通过一个正交矩阵$Q$和它的转置矩阵, 对角化为$\Lambda$.

**Comment by dlutleixin** [comment]
@kf-liu

**Comment by kf-liu** [comment]
> @kf-liu 

收到！不出意外晚上修掉🤣

**Comment by kf-liu** [comment]
第三条今早 merge pr 了，现在已经是对的啦
