### ISSUE TITLE
2 Typo's and a suggestion

### ISSUE THREAD

**Issue by janbaltussen** [kenjihiranabe/The-Art-of-Linear-Algebra#2]
Dear Mr. Hiranabe,

I found two (small) typo's in your github document

1. Sec. 3.5 (p.124) Dimentions (-> dimensions) of the four subspaces
2. This (-> is) the spectral theorem (below Fig. 16).

Wonderfull visualizations!
 
If I may suggest one idea: you number the columns, rows in some images. Why not also number the dots? 

Yes, I realize: the way Gilbert Strang makes us look at matrices, columns, rows, operations is the first (for me: giant) step in understanding linear algebra. In my view, your images make a very compact summarization of it. Thank you!

Jan Baltussen,
The Netherlands

**Comment by kenjihiranabe** [comment]
Thank you Jan, just fixed!
https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/commit/2d207a109981d410cabf1f2d24874d1516a0888f
