### ISSUE TITLE
中文版6.1节翻译错误

### ISSUE THREAD

**Issue by zizz1** [kenjihiranabe/The-Art-of-Linear-Algebra#22]
> 此处“行””列”写反了，如下图

![IMG_2023](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/assets/87361909/65999164-bb4b-47c5-b732-13ea8b0fc891)
![IMG_2024](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/assets/87361909/32fa5d7c-94cc-4e63-996c-be1145a8929e)
![IMG_2025](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/assets/87361909/a3df2be2-e9e5-4d74-ab67-80491096edb2)

**Comment by kenjihiranabe** [comment]
Can you handle this ? @kf-liu

**Comment by kf-liu** [comment]
> Can you handle this ? @kf-liu 

OK no problem
