### ISSUE TITLE
一处错误

### ISSUE THREAD

**Issue by gongchenyear** [kenjihiranabe/The-Art-of-Linear-Algebra#30]
![image](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/assets/60654161/17269167-c0e0-42d6-8328-02373aa2acf4)
此处应为秩1投影矩阵

**Comment by kenjihiranabe** [comment]
@kf-liu can you take care of this ?

**Comment by kf-liu** [comment]
> @kf-liu can you take care of this ?

Sure. I'll check it as soon as possible.
