### ISSUE TITLE
Can you please add tutorial on how to generate PDF? 

### ISSUE THREAD

**Issue by zinwalin** [kenjihiranabe/The-Art-of-Linear-Algebra#5]
on macOS, I installed MacTex, but psselect still not availble. it looks like it's not compatible on macOS.  

what platform and toolchain did you use to generate PDFs? 

Appreciated for your efforts.

**Comment by kenjihiranabe** [comment]
i'm on MacBook.
i'm not sure when pselect is installed but it was include in a  latex package i installed.

pptx -> ps by hand
ps -> ps 's. pselect
ps -> eps ps2eps 

see the makefile.

In any case, my intention is to publish PDF which is in this repo, but not the source code tex file. also eps and  pptx are available in CC0 license .

what is your motivation??
