### ISSUE TITLE
Two typos in English Version of Matrix World

### ISSUE THREAD

**Issue by clvnkhr** [kenjihiranabe/The-Art-of-Linear-Algebra#8]
Hello Mr. Hiranabe, I found Matrix World from Prof. Strang's website. I just note two typos:

1. should be "diagonalizable" in "diagonizable by orthogonal matrix" in the "Normal" section.
2. should be "permutation in "permutaion of I" in the "Permutation" section.

Thank you for the beautiful visualizations. Calvin

**Comment by kenjihiranabe** [comment]
Thanks, Calvin ! You are completely correct. Just corrected.
